### ISSUE TITLE
Spicetify 존재 여부 확인

### ISSUE THREAD

**Issue by aeongdesu** [eungyeole/k-spotify#2]
[ps1 스크립트 #L81](https://github.com/eungyeole/k-spotify/blob/master/scripts/windows-install.ps1#L81) 보니까 존재 여부 확인 안하고 바로 설치 하는것 같습니다.

있는지 확인하고 있으면 다음단계로, 없으면 설치단계 거치는게 나을것 같습니다.

**Comment by SJang1** [comment]
현재 익스텐션 구조 한계상 설치된 Spicetify가 정상적으로 설치된것인지, 현재 설치된 Spicetify 버전이 최신인지 아닌지 두가지를 파악할 수 없는 관계로 존재여부 확인없이 Spicetify 레포지토리에 있는 스크립트로 설치를 진행하고 있습니다.

현재 PC에 설치된 것이 최신버전인지 여부와 정상적으로 작동하는지 확인할 좋은 방법이 있다면 알려주시거나 PR보내주시면 적용해보겠습니다.

**Comment by aeongdesu** [comment]
> 현재 익스텐션 구조 한계상 설치된 Spicetify가 정상적으로 설치된것인지, 현재 설치된 Spicetify 버전이 최신인지 아닌지 두가지를 파악할 수 없는 관계로 존재여부 확인없이 Spicetify 레포지토리에 있는 스크립트로 설치를 진행하고 있습니다.
> 
> 현재 PC에 설치된 것이 최신버전인지 여부와 정상적으로 작동하는지 확인할 좋은 방법이 있다면 알려주시거나 PR보내주시면 적용해보겠습니다.

`%userprofile%\.spicetify` 폴더 있는지 확인하고 `spicetify upgrade` 쓰면 될듯 하네요

**Comment by SJang1** [comment]
> `%userprofile%\.spicetify` 폴더 있는지 확인

`%userprofile%\.spicetify` 폴더의 경우 간혹 정상적으로 삭제가 안되는 경우가 존재하고, spicetify 삭제 방법이 해당 폴더를 삭제하는 것입니다.
사용자가 spicetify 제거를 시도하다 저 폴더만 남겨먹는 경우가 존재할 것 같네요.

> `spicetify upgrade` 쓰면 될듯 하네요

spicetify가 정상 작동하지 않는 환경이면 이 명령어도 정상 작동하지 않을 수 있습니다.. 이런 경우엔 spicetify 재설치를 해야합니다. 이 경우를 확인할 방법이 있을까요?
